## YAML Template.
logging:
    level:
        com.dreamsoftware.iotframesingest: DEBUG

spring:
  kafka:
    client-id: iot-processor
    bootstrap-servers:
      - kafka:9092
    template:
      default-topic: iot-frames
    producer:
      key-serializer: com.dreamsoftware.iotframesingest.serde.SensorKeyDeserializer
      value-serializer: com.dreamsoftware.iotframesingest.serde.SensorDataSerializer
    consumer:
      group-id: iot-processor-consumer
      auto-offset-reset: earliest
      key-deserializer: com.dreamsoftware.iotframesingest.serde.SensorKeySerializer
      value-deserializer: com.dreamsoftware.iotframesingest.serde.SensorDataDeserializer
---
kafka:
  topic:
    input: iot-frames
    output: iot-frames-processed