## YAML Template.
logging:
    level:
        com.dreamsoftware.iotframesingest: TRACE

spring:
  kafka:
    client-id: iot-processor
    bootstrap-servers:
      - kafka:9092
    template:
      default-topic: iot-frames
    consumer:
      group-id: iot-processor-consumer
      auto-offset-reset: earliest
      key-deserializer: com.dreamsoftware.iotframesingest.serde.SensorKeySerializer
      value-deserializer: com.dreamsoftware.iotframesingest.serde.SensorDataDeserializer
---
kafka:
  topic:
    input: iot-frames
    aggregate-metrics-sensor: iot-aggregate-metrics-sensor
    aggregate-metrics-place: iot-aggregate-metrics-place
    metrics-time-series: iot-metrics-time-series
---
info:
    app:
        name: @project.name@
        description: @project.description@
        version: @project.version@
        encoding: @project.build.sourceEncoding@
        java:
            version: @java.version@
---
management:
    endpoint:
        shutdown:
            enabled: true
        health:
            show-details: always
        web:
            exposure.include: '*'
